<?php

return [
    'cols' => [
        'places' => [
            'id' => 'A',
            'name' => 'B',
            'properties' => 'C',
            'image' => 'D',
            'image_title' => 'E',
            'image_desc' => 'F',
            'image_author_link' => 'G',
            'image_gallery' => 'H',
            'image_gallery_title' => 'I',
            'image_gallery_desc' => 'J',
            'image_gallery_author_link' => 'K',
            'page_desc' => 'L',
            'history_desc' => 'M',
            'contact_desc' => 'N',
            'life_hacks' => 'O',
            'helpful_info' => 'P',
            'lat' => 'Q',
            'lng' => 'R',
            'location' => 'S',
        ],
        'hotels' => [
            'id' => 'A',
            'name' => 'B',
            'properties' => 'C',
            'image' => 'D',
            'image_author' => 'E',
            'image_desc' => 'F',
            'image_author_link' => 'G',
            'image_gallery' => 'H',
            'image_gallery_title' => 'I',
            'image_gallery_desc' => 'J',
            'image_gallery_author_link' => 'K',
            'recommended' => 'L',
            'description' => 'M',
            'conditions_accommodation' => 'N',
            'conditions_payment' => 'O',
            'room_desc' => 'P',
            'additional_services' => 'Q',
            'food_desc' => 'R',
            'contact_desc' => 'S',
            'site_link' => 'T',
            'social_links' => 'U',
            'aggregator_links' => 'V',
            'phones' => 'W',
            'location' => 'X',
            'lat' => 'Y',
            'lng' => 'Z',
        ]
    ]
];
